### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by FabianGroeger96** [ShayHill/docx2python#1]
When I try to import your module docx2python, I get this SyntaxError:

```
>>> import docx2python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Kryon Studio\Python\lib\site-packages\docx2python\__init__.py", line 1, in <module>
    from .main import docx2python
  File "C:\Program Files\Kryon Studio\Python\lib\site-packages\docx2python\main.py", line 15, in <module>
    from docx2python.docx_output import DocxContent
  File "C:\Program Files\Kryon Studio\Python\lib\site-packages\docx2python\docx_output.py", line 27
    ) -> None:
    ^
SyntaxError: invalid syntax
```
Can you help me?

**Comment by ShayHill** [comment]
Absolutely. I will attempt to reproduce.

Thank you for the report.

**Comment by ShayHill** [comment]
What is your Python version?

**Comment by FabianGroeger96** [comment]
I'm using python 3.5.

I forked your project and made a version for my python version, it had a problem with the new python syntax.

**Comment by ShayHill** [comment]
Excellent. Thank you.

Going down to Python 3.4 is on my “to do” list.
