### ISSUE TITLE
docx files downloaded from Google Sheets throw error.

### ISSUE THREAD

**Issue by bscs-dev-team** [ShayHill/docx2python#12]
# Issue

Google Sheet documents that are downloaded as `.docx` throw an error when run through the conversion in this function:  `document = docx2python(input_file, html=True)`. If I download the Google Sheet document as a `.docx` file and open it in MS Word and save it, Word adds some data to the file, and the conversion to Python works as expected.

The save format for Google Sheet is called: Office Open XML word processing document

I've included the error traceback below. We've confirmed that the error is happening in the `docx2python()` function call.

Let me know if any other information would be helpful.

## Expected

`.docx` file downloaded from Google Sheet converts to Python. 

## Traceback

Traceback (most recent call last):
  File "/Users/cyee/.local/share/virtualenvs/word-to-md-EFw2UvDn/bin/word2md", line 33, in <module>
    sys.exit(load_entry_point('word2md', 'console_scripts', 'word2md')())
  File "/Users/cyee/.local/share/virtualenvs/word-to-md-EFw2UvDn/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cyee/.local/share/virtualenvs/word-to-md-EFw2UvDn/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cyee/.local/share/virtualenvs/word-to-md-EFw2UvDn/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cyee/.local/share/virtualenvs/word-to-md-EFw2UvDn/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cyee/projects/python/word-to-md/word2md.py", line 349, in cli
    make_md_from_entire_doc(path)
  File "/Users/cyee/projects/python/word-to-md/word2md.py", line 300, in make_md_from_entire_doc
    document = docx2python(input_file, html=True)
  File "/Users/cyee/.local/share/virtualenvs/word-to-md-EFw2UvDn/lib/python3.8/site-packages/docx2python/main.py", line 35, in docx2python
    context = get_context(zipf)
  File "/Users/cyee/.local/share/virtualenvs/word-to-md-EFw2UvDn/lib/python3.8/site-packages/docx2python/docx_context.py", line 272, in get_context
    "docProp2text": collect_docProps(zipf.read("docProps/core.xml")),
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'docProps/core.xml' in the archive"

**Comment by ShayHill** [comment]
Thank you for the report. Can you supply a file that generates this error?

**Comment by bscs-dev-team** [comment]
Hi,

Thanks for the quick response. I've created a Google Doc for testing. Here's the link: https://docs.google.com/document/d/1cE1rm2QVhDr9o2nwb_botuMDG-83B6tpvlSyEbedAPg/edit?usp=sharing.

When it's downloaded as a `.docx` it is initially about 7000 bytes in size and the conversion to python errors as shown above. I open it, add a space character and then delete the space character so I can save it as edited. Once that saves, the file is about 13000 bytes and the conversion to python works as expected.

**Comment by ShayHill** [comment]
Thank you. I will have a look.

**Comment by ShayHill** [comment]
Does v1.27 meet your requirements?

---- version 1.27 - 201102 Continue when document properties are not found

`docx2python(file).properties` returns a dictionary of document properties (e.g., {'Author': 'Shay Hill'}). Google Docs
(and perhaps others) do not store such properties. When document properties cannot be found, v1.27 will continue and
return an empty dictionary for `docx2python(file).properties`.

This will only happen where the program would previously have failed with a KeyError, so no previous behavior (which
allowed the program to complete) has been altered.

**Comment by bscs-dev-team** [comment]
version1.27 fixes this for us. We were just wrapping a try/except for the KeyError. Thanks for getting this fixed so quickly!

**Comment by ShayHill** [comment]
Glad to hear it, and thank you again for identifying this.
