### ISSUE TITLE
Feature to work with Comments

### ISSUE THREAD

**Issue by flyguy62n** [ShayHill/docx2python#52]
Using Docx2Python in a data discovery tool to find PII and other sensitive data.  Reading comments in DOCX files would be fantastic.  I've attached a sample file.  For my part, it doesn't need to be fancy -- even returning comments and their responses as a list of strings would do the trick.  

[lorem-ipsum-1line-comments.docx](https://github.com/ShayHill/docx2python/files/14805109/lorem-ipsum-1line-comments.docx)

**Comment by ShayHill** [comment]
I've deployed 2.9.0 to test PyPI.

```
    pars = docx2python(RESOURCES / "comments.docx")
    comments = pars.comments
    pars.close()
    pars.comments => [
        (reference text, author, date, comment text),
        ....
    ]
```

It seems to work, but I don't have a lot of docx files with comments  to test. I'm going to look around for some old, ugly files full of comments to test before I upload to official PyPI.

**Comment by flyguy62n** [comment]
I probably have some files I can throw at it too.  If I get a hance this weekend, I'll give it a shot and let you know.  First part of next week at the latest.

**Comment by ShayHill** [comment]
Sounds great. Thank you.

Sent from my iPhone

On Mar 29, 2024, at 19:27, Randy Bartels ***@***.***> wrote:

﻿

I probably have some files I can throw at it too. If I get a hance this weekend, I'll give it a shot and let you know. First part of next week at the latest.

**Comment by flyguy62n** [comment]
Finally got to this today.  A couple of notes:

1. Using Python 3.12.2 on Windows
2. On the attached file, the actual hyperlink in the comment points to www.gooogle.com, but `pars.comments` notes it as `href="styles.xml"`.  Pretty minor, but if there's some magic to put the real `href` in there....
[test_file_with_comments.docx](https://github.com/ShayHill/docx2python/files/14843886/test_file_with_comments.docx)

3. On the second file I tried I got a traceback.  Unfortunately, I can't upload it as it has real customer data in it.  To draw some contrast:

- I was able to load the `text` using v2.8.0, but not with 2.9.1.
- An attempt to read `text` from this file using 2.9.1 also generated an exception.
- I was able to read both `comment` and `text` from similar files created from the same template using 2.9.1.

If there's other info I can provide about the offending file, just let me know.

`comments traceback:`
```
>>> comments=pars.comments
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_output.py", line 266, in comments
    depth_collector = office_document.depth_collector
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_reader.py", line 237, in depth_collector
    self.__depth_collector = self.__depth_collector or new_depth_collector(self)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 384, in new_depth_collector
    branches(root)
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 380, in branches
    branches(branch)
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 380, in branches
    branches(branch)
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 380, in branches
    branches(branch)
  [Previous line repeated 1 more time]
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 376, in branches
    recurse_into_tree = tag_runner.open(tree)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 139, in open
    return method(tree)
           ^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 183, in _open_comment_range_start
    self.tables.start_comment_range(tree.attrib[qn("w:id")])
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\depth_collector.py", line 127, in start_comment_range
    cruns = self._count_runs()
            ^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\depth_collector.py", line 120, in _count_runs
    return len(list(self._runs_so_far))
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\depth_collector.py", line 108, in _runs_so_far
    assert len(self.open_pars) == 1
AssertionError
```

`text=pars.text traceback:`
```
>>> text=pars.text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_output.py", line 212, in text
    return flatten_text(self.document_runs, do_pStyle)
                        ^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_output.py", line 199, in document_runs
    + self.body_runs
      ^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_output.py", line 155, in body_runs
    return self.officeDocument_runs
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_output.py", line 145, in officeDocument_runs
    return self._get_runs("officeDocument")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_output.py", line 120, in _get_runs
    content += file.content
               ^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_reader.py", line 246, in content
    return self.get_content()
           ^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_reader.py", line 259, in get_content
    return cast(TablesList, self.depth_collector.tree)
                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_reader.py", line 237, in depth_collector
    self.__depth_collector = self.__depth_collector or new_depth_collector(self)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 384, in new_depth_collector
    branches(root)
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 380, in branches
    branches(branch)
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 380, in branches
    branches(branch)
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 380, in branches
    branches(branch)
  [Previous line repeated 1 more time]
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 376, in branches
    recurse_into_tree = tag_runner.open(tree)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 139, in open
    return method(tree)
           ^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\docx_text.py", line 183, in _open_comment_range_start
    self.tables.start_comment_range(tree.attrib[qn("w:id")])
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\depth_collector.py", line 127, in start_comment_range
    cruns = self._count_runs()
            ^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\depth_collector.py", line 120, in _count_runs
    return len(list(self._runs_so_far))
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\temp\.docx2python\Lib\site-packages\docx2python\depth_collector.py", line 108, in _runs_so_far
    assert len(self.open_pars) == 1
AssertionError
```

**Comment by ShayHill** [comment]
Both of these should be fixed now. Please let me know if you see the same failures with 2.9.2

**Comment by flyguy62n** [comment]
That did it.  Both text and comments properly parsed in 2.9.2.  Thanks!
