### ISSUE TITLE
Error: Invalid tag name '<cyfunction Comment at 0x12345678abcd> for multiple documents

### ISSUE THREAD

**Issue by iamohcy** [ShayHill/docx2python#72]
Hi, I was hoping to get some help with the above error, I'm seeing it occur for about 5% of documents that I'm processing. Unfortunately I cannot share the documents for data sensitivity reasons, but if you have any ideas as to what might be causing it that would be a great help!

```
[ERROR] ValueError: Invalid tag name '<cyfunction Comment at 0x12345678abcd>'
Traceback (most recent call last):
  File "./python/lib/python3.11/site-packages/datadog_lambda/wrapper.py", line 126, in __call__
  File "./python/lib/python3.11/site-packages/datadog_lambda/wrapper.py", line 240, in __call__
  File "/var/task/index.py", line 325, in handler
    raise e
  File "/var/task/index.py", line 296, in handler
    text: str = extract_text_from_docx(obj["Body"].read())
  File "/var/task/index.py", line 125, in extract_text_from_docx
    return parsed_document.text
  File "/opt/python/docx2python/docx_output.py", line 358, in text
    return flatten_text(self.document_runs)
  File "/opt/python/docx2python/docx_output.py", line 280, in document_runs
    + self.body_runs
  File "/opt/python/docx2python/docx_output.py", line 254, in body_runs
    return self.officeDocument_runs
  File "/opt/python/docx2python/docx_output.py", line 244, in officeDocument_runs
    return get_par_strings(self.officeDocument_pars)
  File "/opt/python/docx2python/docx_output.py", line 180, in officeDocument_pars
    return self._get_pars("officeDocument")
  File "/opt/python/docx2python/docx_output.py", line 155, in _get_pars
    content += file.content
  File "/opt/python/docx2python/docx_reader.py", line 250, in content
    return self.get_content()
  File "/opt/python/docx2python/docx_reader.py", line 268, in get_content
    return self.depth_collector.tree
  File "/opt/python/docx2python/docx_reader.py", line 241, in depth_collector
    self.__depth_collector = self.__depth_collector or new_depth_collector(self)
  File "/opt/python/docx2python/docx_text.py", line 373, in new_depth_collector
    root = root if root is not None else file.root_element
  File "/opt/python/docx2python/docx_reader.py", line 221, in root_element
    merge_elems(self, root)
  File "/opt/python/docx2python/merge_runs.py", line 154, in merge_elems
    elems = [x for x in tree if has_content(x)]
  File "/opt/python/docx2python/merge_runs.py", line 154, in <listcomp>
    elems = [x for x in tree if has_content(x)]
  File "/opt/python/docx2python/attribute_register.py", line 343, in has_content
    return next(iter_content(tree), None)
  File "/opt/python/docx2python/attribute_register.py", line 338, in iter_content
    if _is_content(tree_):
  File "/opt/python/docx2python/attribute_register.py", line 313, in _is_content
    return get_prefixed_tag(elem) in _CONTENT_TAGS
  File "/opt/python/docx2python/attribute_register.py", line 77, in get_prefixed_tag
    return f"{elem.prefix}:{get_localname(elem)}"
  File "/opt/python/docx2python/attribute_register.py", line 42, in get_localname
    qname = etree.QName(elem.tag)
  File "src/lxml/etree.pyx", line 1871, in lxml.etree.QName.__init__
  File "src/lxml/apihelpers.pxi", line 1731, in lxml.etree._tagValidOrRaise
```

**Comment by ShayHill** [comment]
Interesting, because docx2python should ignore tags it cannot recognize. Looks like something in lxml.  I could probably fix it, but I’d have to be able to reproduce it. Can you sanitize one of the files and send it?

I’m also curious what you know about the history of these files. Were they created in Word? Open Office? Something from Google?

On Sep 25, 2024, at 23:33, iamohcy ***@***.***> wrote:

﻿

Hi, I was hoping to get some help with the above error, I'm seeing it occur for about 5% of documents that I'm processing. Unfortunately I cannot share the documents for data sensitivity reasons, but if you have any ideas as to what might be causing it that would be a great help!

[ERROR] ValueError: Invalid tag name '<cyfunction Comment at 0x12345678abcd>'
Traceback (most recent call last):
  File "./python/lib/python3.11/site-packages/datadog_lambda/wrapper.py", line 126, in __call__
  File "./python/lib/python3.11/site-packages/datadog_lambda/wrapper.py", line 240, in __call__
  File "/var/task/index.py", line 325, in handler
    raise e
  File "/var/task/index.py", line 296, in handler
    text: str = extract_text_from_docx(obj["Body"].read())
  File "/var/task/index.py", line 125, in extract_text_from_docx
    return parsed_document.text
  File "/opt/python/docx2python/docx_output.py", line 358, in text
    return flatten_text(self.document_runs)
  File "/opt/python/docx2python/docx_output.py", line 280, in document_runs
    + self.body_runs
  File "/opt/python/docx2python/docx_output.py", line 254, in body_runs
    return self.officeDocument_runs
  File "/opt/python/docx2python/docx_output.py", line 244, in officeDocument_runs
    return get_par_strings(self.officeDocument_pars)
  File "/opt/python/docx2python/docx_output.py", line 180, in officeDocument_pars
    return self._get_pars("officeDocument")
  File "/opt/python/docx2python/docx_output.py", line 155, in _get_pars
    content += file.content
  File "/opt/python/docx2python/docx_reader.py", line 250, in content
    return self.get_content()
  File "/opt/python/docx2python/docx_reader.py", line 268, in get_content
    return self.depth_collector.tree
  File "/opt/python/docx2python/docx_reader.py", line 241, in depth_collector
    self.__depth_collector = self.__depth_collector or new_depth_collector(self)
  File "/opt/python/docx2python/docx_text.py", line 373, in new_depth_collector
    root = root if root is not None else file.root_element
  File "/opt/python/docx2python/docx_reader.py", line 221, in root_element
    merge_elems(self, root)
  File "/opt/python/docx2python/merge_runs.py", line 154, in merge_elems
    elems = [x for x in tree if has_content(x)]
  File "/opt/python/docx2python/merge_runs.py", line 154, in <listcomp>
    elems = [x for x in tree if has_content(x)]
  File "/opt/python/docx2python/attribute_register.py", line 343, in has_content
    return next(iter_content(tree), None)
  File "/opt/python/docx2python/attribute_register.py", line 338, in iter_content
    if _is_content(tree_):
  File "/opt/python/docx2python/attribute_register.py", line 313, in _is_content
    return get_prefixed_tag(elem) in _CONTENT_TAGS
  File "/opt/python/docx2python/attribute_register.py", line 77, in get_prefixed_tag
    return f"{elem.prefix}:{get_localname(elem)}"
  File "/opt/python/docx2python/attribute_register.py", line 42, in get_localname
    qname = etree.QName(elem.tag)
  File "src/lxml/etree.pyx", line 1871, in lxml.etree.QName.__init__
  File "src/lxml/apihelpers.pxi", line 1731, in lxml.etree._tagValidOrRaise

**Comment by iamohcy** [comment]
Having issues sanitizing the file just saving the file again in MS Word will make the issue disappear. Will try to find out how they were generated thanks! For the list index out of range issue, will try to sanitize a file and get that to you.

**Comment by ShayHill** [comment]
Thank you for bringing this up. These kinds of issues have come up before. The files may have been converted from pdf at some point.

If opening and saving the file in Word corrects the issue, then that's probably the best way to address it. If there are many such files, this could be accomplished with a PowerShell script.

**Comment by ShayHill** [comment]
I’ll have a look. Do you know anything about the history of the file?

On Dec 4, 2024, at 20:56, makretch ***@***.***> wrote:

﻿

Hi @ShayHill<https://github.com/ShayHill> - I'm struggling with a similar issue. A relevant example can be found here in case you'd like to reproduce (see attachment at bottom of page): https://sam.gov/opp/866427911c9b4965ac70496356d48a7b/view. Thank you!

**Comment by ShayHill** [comment]
> Hi @ShayHill - I'm struggling with a similar issue. A relevant example can be found here in case you'd like to reproduce (see attachment at bottom of page): https://sam.gov/opp/866427911c9b4965ac70496356d48a7b/view. Thank you!

Thank you for the file. It appears a conversion from ASPOSE introduced an invalid xml tag. The tag was only for a comment. Something along the lines of `converted by ASPOSE`. I've updated Docx2Python to skip those tags and issue a warning instead of raising a ValueError. Version 3.3.0 on PyPI will now extract text from the document at sam.gov with a warning.

**Comment by makretch** [comment]
Thanks for the quick fix, @ShayHill!
