### ISSUE TITLE
Error when parsing ContentControl in table

### ISSUE THREAD

**Issue by iamohcy** [ShayHill/docx2python#73]
Hi, mentioning this in a new issue since it seems unrelated to the [earlier](https://github.com/ShayHill/docx2python/issues/72) issue. We also noticed that when there's a ContentControl dropdown selector within the table, we get the following error:

```
[ERROR] IndexError: list index out of range
Traceback (most recent call last):
  File "./python/lib/python3.11/site-packages/datadog_lambda/wrapper.py", line 126, in __call__
  File "./python/lib/python3.11/site-packages/datadog_lambda/wrapper.py", line 240, in __call__
  File "/var/task/index.py", line 325, in handler
    raise e
  File "/var/task/index.py", line 296, in handler
    text: str = extract_text_from_docx(obj["Body"].read())
  File "/var/task/index.py", line 125, in extract_text_from_docx
    return parsed_document.text
  File "/opt/python/docx2python/docx_output.py", line 358, in text
    return flatten_text(self.document_runs)
  File "/opt/python/docx2python/docx_output.py", line 280, in document_runs
    + self.body_runs
  File "/opt/python/docx2python/docx_output.py", line 254, in body_runs
    return self.officeDocument_runs
  File "/opt/python/docx2python/docx_output.py", line 244, in officeDocument_runs
    return get_par_strings(self.officeDocument_pars)
  File "/opt/python/docx2python/docx_output.py", line 180, in officeDocument_pars
    return self._get_pars("officeDocument")
  File "/opt/python/docx2python/docx_output.py", line 155, in _get_pars
    content += file.content
  File "/opt/python/docx2python/docx_reader.py", line 250, in content
    return self.get_content()
  File "/opt/python/docx2python/docx_reader.py", line 268, in get_content
    return self.depth_collector.tree
  File "/opt/python/docx2python/docx_reader.py", line 241, in depth_collector
    self.__depth_collector = self.__depth_collector or new_depth_collector(self)
  File "/opt/python/docx2python/docx_text.py", line 390, in new_depth_collector
    branches(root)
  File "/opt/python/docx2python/docx_text.py", line 386, in branches
    branches(branch)
  File "/opt/python/docx2python/docx_text.py", line 386, in branches
    branches(branch)
  File "/opt/python/docx2python/docx_text.py", line 386, in branches
    branches(branch)
  [Previous line repeated 1 more time]
  File "/opt/python/docx2python/docx_text.py", line 388, in branches
    tag_runner.close(tree)
  File "/opt/python/docx2python/docx_text.py", line 158, in close
    method(tree)
  File "/opt/python/docx2python/docx_text.py", line 335, in _close_table_cell
    prev_tr = this_tbl[-2]
```

Example of what the dropdown looks like.
![image](https://github.com/user-attachments/assets/65bcdfad-c407-45a9-a00c-4c9149309127)

I've sanitized and attached a copy of the file that triggers this error here:
[test_list_index_a.docx](https://github.com/user-attachments/files/17143877/test_list_index_a.docx)

**Comment by ShayHill** [comment]
Thank you for raising this.

This is addressed in version 3.0.2

commit d7f1e34ea8f9b240aad235903915fdf7ba7e6584
Author: Shay <shay_public@hotmail.com>
Date:   Thu Sep 26 10:13:50 2024 -0500

    fix: ignore first row vMerge flags in tbl

    Dropdown lists in table cells are written into the xml as nested tables
    with a vMerge request in the first row. Docx2Python attempted to copy
    values from a previous row to satisfy such vMerge requests. This failed,
    because there was no previous row from which to copy. Docx2Python now
    ignores vMerge requests in the first row of any table.

    closes docx2python/issues/73
